sudo: required
language: generic
services:
  - docker

before_install: 
  - docker build -t umesjajoo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true umesjajoo/docker-react npm run test