name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t umesjajoo/docker-react -f Dockerfile.dev .
      
    - name: Build Docker Test
      run: docker run -e CI=true umesjajoo/docker-react npm run test
      
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'
      
    - name: Elastic Beanstalk Deploy
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: docker-react
        environment_name: Dockerreact-env
        version_label: docker-react-v1
        region: us-east-1
        deployment_package: deploy.zip
      
